### ISSUE TITLE
Create new project - WildFly Swarm - REST and RH SSO - fails

### ISSUE THREAD

**Issue by ldimaggi** [wildfly-swarm-openshiftio-boosters/wfswarm-rest-http#12]
See details here:
https://github.com/fabric8-ui/fabric8-ui/issues/1674

**Comment by rdruss** [comment]
Related to an existing issue adopting the Fabric8 Jenkins Pipeline Library:
https://github.com/openshiftio/appdev-planning/issues/35

**Comment by kenfinnigan** [comment]
Closing as not applicable to the booster
