### ISSUE TITLE
Create a new project - Wildfly HTTP - fails

### ISSUE THREAD

**Issue by ldimaggi** [wildfly-swarm-openshiftio-boosters/wfswarm-rest-http#13]
See details here:
https://github.com/fabric8-ui/fabric8-ui/issues/1672

**Comment by rdruss** [comment]
Related to an existing issue adopting the Fabric8 Jenkins Pipeline Library:
https://github.com/openshiftio/appdev-planning/issues/35

**Comment by kenfinnigan** [comment]
@ldimaggi can you confirm whether https://github.com/openshiftio/openshift.io/issues/398 has been tested with newer Boosters and is still an issue?

**Comment by Ladicek** [comment]
This is still an issue, but not in Swarm: https://github.com/fabric8io/fabric8-team-components/issues/119

**Comment by kenfinnigan** [comment]
@Ladicek, would you see these as closable then as it's completely outside the scope of WF Swarm?

**Comment by Ladicek** [comment]
@kenfinnigan I didn't check Swarm boosters on OSIO for some time, but last time I did, Swarm itself worked just fine (after working around one issue in JBoss Modules) and there were just 2 issues on Fabric8 side that had to be solved. One has been fixed already, the other one is still open.

So yes, I believe these issues in Swarm boosters can be closed from my POV.

**Comment by kenfinnigan** [comment]
Closing as not applicable to the booster
