### ISSUE TITLE
Create a new project - Wildfly Swarm - fails

### ISSUE THREAD

**Issue by ldimaggi** [wildfly-swarm-openshiftio-boosters/wfswarm-rest-http#14]
See details here:
https://github.com/fabric8-ui/fabric8-ui/issues/1671

**Comment by rdruss** [comment]
Related to an existing issue adopting the Fabric8 Jenkins Pipeline Library:
https://github.com/openshiftio/appdev-planning/issues/35

**Comment by kenfinnigan** [comment]
Closing as not applicable to the booster
